[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
models.workspace = true
log.workspace = true
serde_json.workspace = true
console_error_panic_hook = "0.1.7"
gloo-net = "0.2.5"
patternfly-yew = "0.3"
wasm-bindgen-futures = "0.4.33"
wasm-logger = "0.2.0"
yew = { version = "0.20.0", features = [ "csr" ]}
yew-router = "0.17.0"
