[workspace]
members = [ "server", "frontend", "models" ]

[workspace.dependencies]
models = { path = "./models" }
log = "0.4.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
rand = "0.8"